name: Wake Streamlit App

# Trigger every 15 minutes (optimal to prevent Streamlit sleep)
on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes UTC
  workflow_dispatch:         # allows manual trigger

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run wake script
        run: |
          python wake.py
